name: mixswap_sdk_dart
description: MixSwap API for Dart/Flutter.
version: 0.0.1
homepage: https://github.com/MixinNetwork/mixswap_sdk_dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^4.0.0
  json_annotation: ^4.0.1
  equatable: ^2.0.3

dev_dependencies:
  test: ^1.17.9
  very_good_analysis: ^2.1.2
  build_runner:
  json_serializable: ^5.0.0
  
